### ISSUE TITLE
Disable message send button when the message is empty

### ISSUE THREAD

**Issue by afeefuddin** [algovengers/Hairify#110]
![image](https://github.com/algovengers/Hairify/assets/126336384/ce1ac5c9-781c-42b4-9dce-c69ec5117498)

**Comment by SuperSahitya** [comment]
Hello @afeefuddin . I request you to assign me the issue. I have  I will be happy to fix this issue and will try to create the required PR by tonight.

Looking forward to contributing to this project!

**Comment by Raghavi-22** [comment]
As a contributor of GSSOC'24 I would like to work on this issue.
Could you assign me this @afeefuddin

**Comment by Ketanop321** [comment]
As a contributor of GSSOC'24 I would like to work on this issue 
Could you assign me this @afeefuddin

**Comment by Ketanop321** [comment]
Sir @afeefuddin , I request you to assign me the issue. It will be a great learning for me to fix this issue .
Looking forward to contributing to this project

**Comment by tuwid-Ashish** [comment]
Hii @afeefuddin  

I'd love to tackle issue on the chatbot .  I noticed it's still open and this problem is not resolved at frontend and generating unnecessary calling to chatbot api . This issue would be great chance for me to start contributing is this project

**Comment by nishant0708** [comment]
can you assign me this issue under gssoc 24.

**Comment by afeefuddin** [comment]
Sorry, I forgot about this issue. Assigning @SuperSahitya first. Please make the PR within 3 days, else I'll assign the next person.

**Comment by RutvikMaheshwari** [comment]
Is the issue is still open, Please assign me to resolve for gssoc 24
