### ISSUE TITLE
Updating UI of Login and Signup

### ISSUE THREAD

**Issue by Sailesh3000** [algovengers/Hairify#114]
UI does not look interactive and attractive I can update it I am GSSOC'24 Contributor please assign me this issue
![image](https://github.com/algovengers/Hairify/assets/126142666/fc58e0f8-321d-4452-b2a4-8acd54348ef4)
I can make something like this 
![image](https://github.com/algovengers/Hairify/assets/126142666/df49d5cd-b30f-4e26-a17a-01ac3ebdbb47)

**Comment by afeefuddin** [comment]
We are satisfied with the current UI and it has been recently updated. Thanks @Sailesh3000 for making this issue. Closing this for now.
