### ISSUE TITLE
[Feature] Missing Review Page 

### ISSUE THREAD

**Issue by Manav173** [algovengers/Hairify#115]
Problem:
Currently, the website lacks a dedicated space for users to provide feedback or report any issues they encounter while using the platform.

Solution:
Implement a review page which will serve as a centralized hub for collecting user feedback, enabling us to enhance the user experience and resolve any issues efficiently.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @algovengers  .

**Comment by afeefuddin** [comment]
I don't think this is there in our plans anytime soon.
