### ISSUE TITLE
[BUG] Login is failing with status code 401

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [algovengers/Hairify#119]
When i am clicking on the login button then it fails with status code 401 and  don't let me in the website .
![Screenshot 2024-05-18 113329](https://github.com/algovengers/Hairify/assets/118350936/ffd5ab53-bee5-4623-96e0-daa5cc8ab32d)

**Comment by afeefuddin** [comment]
Have you put in the creditnals correctly?

**Comment by Ayushmaanagarwal1211** [comment]
Yes actually when i did signup then it is saved in chrome and at the time of login the creadentials was used by chrome automatically so the credentials are correct or if bychance the credentials are wrong then wrong creadentials popup should be shown according to me

**Comment by afeefuddin** [comment]
Probably a bug on production.
