### ISSUE TITLE
Adding an image support to the prompt in the chat AI feature

### ISSUE THREAD

**Issue by Raghavi-22** [algovengers/Hairify#124]
![Screenshot 2024-05-18 220015](https://github.com/algovengers/Hairify/assets/118007421/7be25429-b2d2-4959-bbd7-332cef957f98)
Want to implement similar way to gemini image support for user prompt 
here
![Screenshot 2024-05-18 220028](https://github.com/algovengers/Hairify/assets/118007421/afebfe55-9e7a-4910-a03e-a56b01456f2c)
Could you assign me this issue under GSSOC'24.

**Comment by afeefuddin** [comment]
We already have a feature to generate report with image and chat with image is not possible with gemini LLM
