### ISSUE TITLE
Improving UI of chat AI feature

### ISSUE THREAD

**Issue by Raghavi-22** [algovengers/Hairify#125]
![Screenshot 2024-05-18 220028](https://github.com/algovengers/Hairify/assets/118007421/25015e33-4af5-424e-824d-01944b1d38d4)
Adding corner radius to the prompt bar make it visually appealing than plain rectangle like the one in gemini
![Screenshot 2024-05-18 215718](https://github.com/algovengers/Hairify/assets/118007421/e48124ee-58f4-4f71-943d-ef9a20d89297)
Could you assign it to me under GSSOC'24

**Comment by afeefuddin** [comment]
Duplicated Issue
