### ISSUE TITLE
After passing invalid email id server responding 400 which is fine but I think when user input invalid email we should show message at time of registration only

### ISSUE THREAD

**Issue by kapilG0** [algovengers/Hairify#131]
When user enter invalid email we should handle on frontend only this thing reduce the server call 
![Screenshot_20240519_180051](https://github.com/algovengers/Hairify/assets/59639410/4225ed06-8694-4efd-b867-40c0cc6e0b5a)

**Comment by kapilG0** [comment]
Hello @algovengers please assign this issue to me under gssoc 24

**Comment by afeefuddin** [comment]
Duplicate
