### ISSUE TITLE
[Feat]: reCAPTCHA Implementation

### ISSUE THREAD

**Issue by antriksh-9** [algovengers/Hairify#135]
**Description:**

Implementing reCAPTCHA on the website will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This also helps in preventing automated bots from accessing or submitting forms on the website.

**Solution:**

I would consider using reCAPTCHA v3, which provides a more user-friendly way to detect bots without requiring any interaction from the user.
I will prefer integrating reCAPTCHA in signup page as it will help prevent bot registrations on the site.

![Screenshot 2024-05-18 113014](https://github.com/algovengers/Hairify/assets/132576984/c476f813-fe6d-422e-af59-73f7c9ec24bf)

**Comment by antriksh-9** [comment]
Hey @afeefuddin, I want to work on this issue. 
Please assign it to me.

**Comment by afeefuddin** [comment]
Not required
