### ISSUE TITLE
Navbar Redirects to Homepage Unintentionally

### ISSUE THREAD

**Issue by Abh-I-seK** [algovengers/Hairify#137]
Ideally clicking on the region shown below should not do anything but its redirecting me to homepage.

![Screenshot 2024-05-22 145127](https://github.com/algovengers/Hairify/assets/134422863/2d837b10-8cf7-4d0a-91cf-c959db966385)

Could you please assign this issue to me under GSSOC 24.

**Comment by afeefuddin** [comment]
Assigned @Abh-I-seK
