### ISSUE TITLE
Add Issue template 

### ISSUE THREAD

**Issue by aasthakourav20** [algovengers/Hairify#139]
Adding an issue template to a project repository is necessary for several reasons. Firstly, it standardizes the way issues are reported, ensuring that all the relevant information is provided upfront. This reduces the back-and-forth communication often required to gather essential details, thereby saving time for both the reporters and the maintainers. Additionally, a well-structured issue template helps in categorizing and prioritizing issues effectively, making the management of bugs, feature requests, and other tasks more efficient. It also promotes a more organized and professional approach to project maintenance, which can enhance collaboration among contributors and improve the overall quality of the project.

Kindly assign this issue to me under GSSoC'24 .

**Comment by afeefuddin** [comment]
Duplicate Issue
