### ISSUE TITLE
color combination

### ISSUE THREAD

**Issue by devlohani99** [algovengers/Hairify#142]
![Screenshot 2024-05-24 013114](https://github.com/algovengers/Hairify/assets/142163543/e6d0b92c-a811-4ef3-a8a7-6288cab22113)
the background effect of the text can be improve

**Comment by devlohani99** [comment]
@sanjay-kv @subharthihazra @Madhu-mac kindly assign me

**Comment by afeefuddin** [comment]
Tagging people without specifying the issue briefly won't help, please share the design if you have something better than the current one.
