### ISSUE TITLE
Implementing Multilingual support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [algovengers/Hairify#150]
I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.
The below image is my last project where I made it available in different languages.
![image](https://github.com/algovengers/Hairify/assets/139578011/59d95ef5-8cb4-4019-a45f-d125edf30b39)

**Comment by afeefuddin** [comment]
Not required.
