### ISSUE TITLE
Error message are not clearly visible 

### ISSUE THREAD

**Issue by shifa-s11** [algovengers/Hairify#155]
error message should be something like toasters and there should be customize messages which user can understand and change there colors also , these are not even visible 
![Screenshot (48)](https://github.com/algovengers/Hairify/assets/144918231/fc4ae005-079e-4a83-bc1f-93c448f00997)

**Comment by shifa-s11** [comment]
i really wanted to contribute to this project

**Comment by afeefuddin** [comment]
Duplicate Issue
