### ISSUE TITLE
Signup form not visually appealing should add some image 

### ISSUE THREAD

**Issue by shifa-s11** [algovengers/Hairify#156]
should add some image and effects  in signup forms to make it visually appealing

**Comment by shifa-s11** [comment]
please assign this issue to me , i really want to contribute to this project

**Comment by afeefuddin** [comment]
Please share the design on how will you improve the signup page.

**Comment by shifa-s11** [comment]
![Screenshot (50)](https://github.com/algovengers/Hairify/assets/144918231/4da562fe-3400-4217-9008-9483cceb3678)
like this colors and image will be adjusted according to the theme of the website

**Comment by afeefuddin** [comment]
No we are good with the current one.
