### ISSUE TITLE
No button to go back to Home 

### ISSUE THREAD

**Issue by YukiP7** [algovengers/Hairify#162]
While exploring the website, I noticed that when I opened the Dashboard, there was no option to go back to the home page. I think it would be helpful to add buttons for the home and about sections so that users can easily navigate and understand the purpose of the website.

![Screenshot 2024-05-31 155824](https://github.com/algovengers/Hairify/assets/109288720/543ba652-212a-4cd1-8086-af646e8c1a82)

I am willing to contribute to this issue. Please assign it to me with appropriate labels of GSSOC and its level.

**Comment by YukiP7** [comment]
@afeefuddin  @algovengers  Please assign me this issue under the label 'gssoc' with the appropriate level.

**Comment by riteshpushkar** [comment]
There is no need for back button as you can click on hairify or moreover anywhere in that row you'll be forwarded to home page only
