### ISSUE TITLE
About Page 

### ISSUE THREAD

**Issue by YukiP7** [algovengers/Hairify#163]
Adding an "About" page to the website will be beneficial as it will allow users to gain insight into the purpose and mission of the website. This will help in creating a more engaging and informative user experience.

**Comment by YukiP7** [comment]
@afeefuddin @algovengers Please assign me this issue under gssoc and its appropriate levels.

**Comment by afeefuddin** [comment]
Duplicate Issue #42, ask for assignment in the original issue.
