### ISSUE TITLE
BUG : Chat with AI is not working 

### ISSUE THREAD

**Issue by YukiP7** [algovengers/Hairify#164]
As I opened the chatbot feature, I was unable to find any output from the chatbot. It also didn't accept user inputs and displayed an error while loading. I can resolve this issue. Please assign it to me. I can add chatbot greetings, provide suggestions for user queries, and help users learn more about their hair type.

![Screenshot 2024-05-31 160103](https://github.com/algovengers/Hairify/assets/109288720/49997903-2c5f-4ccc-9b1b-4c00c492d7bf)

Please assign me this issue under 'level3' and 'gssoc' labels .

**Comment by YukiP7** [comment]
@afeefuddin  @algovengers  Please assign me this issue under 'level3' and 'gssoc' labels .

**Comment by afeefuddin** [comment]
The issue is with our deployment and we are facing some connection pooling issue with DB
