### ISSUE TITLE
BUG: Not giving any toaster message of login and any unappropriated activity notification 

### ISSUE THREAD

**Issue by YukiP7** [algovengers/Hairify#165]
As I was reviewing the website, I noticed that users are not receiving any notifications or success/failure messages when signing in or logging into the website. Additionally, I observed that there are no error messages displayed when inputting data to generate a report on the AI page. If I don't upload an image, the form does not submit, but it also does not show any error indicating that no image was uploaded.

Please assign me this issue under gssoc with level2 .

**Comment by YukiP7** [comment]
@afeefuddin  @algovengers Please assign me this issue

**Comment by afeefuddin** [comment]
Duplicate issue
