### ISSUE TITLE
[BUG]: The login form needs a message updation

### ISSUE THREAD

**Issue by Varsha010101** [algovengers/Hairify#173]
When a user tries to login with wrong email or password a valid message must be displayed. It displays an inappropriate message leaving users blank about the reason. Also to add a message as successfully logged in. 
![Screenshot 2024-06-05 225756](https://github.com/algovengers/Hairify/assets/142898488/82788cd2-bbab-4c1f-b163-84c8a2ea2c5f)
Kindly review this issue and label it under GSSoC @algovengers

**Comment by afeefuddin** [comment]
Duplicate
