### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by afeefuddin** [algovengers/Hairify#39]
The redirect after login should be instant, and not slow.
Currently, there is a delay after successful login before redirect.

**Comment by ronisarkarexe** [comment]
@afeefuddin can you assign me this issue?

**Comment by afeefuddin** [comment]
An issue has been assigned to you, we assign one issue at a time to new contributors.

**Comment by vidhikapadia2799** [comment]
Hi @afeefuddin ,  I want to work on this issue. Please assign this issue to me under GSSoC'24.

**Comment by afeefuddin** [comment]
Sure @vidhikapadia2799, assigned to you.

**Comment by afeefuddin** [comment]
Any updates @vidhikapadia2799?

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by afeefuddin** [comment]
Hey @nishant0708 you want to work on this issue?

**Comment by nishant0708** [comment]
Yess

**Comment by afeefuddin** [comment]
I believe this issue can be resolved by adding a toast notifications instead since the delay is there because of switching the page. We can add a loader also.

**Comment by nishant0708** [comment]
Okay I will look into it
