### ISSUE TITLE
Adding Animation to the Home page images 

### ISSUE THREAD

**Issue by Madhu-mac** [algovengers/Hairify#43]
The website looks killer. We can add animations to the images in the home page using `motion.div`. It will add more presence to the website.

Expected Behaviour:

Demo project: https://coursehub-admin.netlify.app/

**Comment by Madhu-mac** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by afeefuddin** [comment]
Sure, but please keep it simple and don't add too much animations.

**Comment by SumitKumar-17** [comment]
@afeefuddin I want to work on this issue. Can you assign this issue to me under GSSoc'24?
I want to create a animation like a small up and down ease effect . so that the image moves.
I am adding a link to one of my projects Home page . you can check it on that .https://ocms-frontend.vercel.app/

**Comment by Madhu-mac** [comment]
> @afeefuddin I want to work on this issue. Can you assign this issue to me under GSSoc'24? I want to create a animation like a small up and down ease effect . so that the image moves. I am adding a link to one of my projects Home page . you can check it on that .https://ocms-frontend.vercel.app/

It is already assigned to me, I'm currently working on this rn

**Comment by afeefuddin** [comment]
Hey, @Madhu-mac. Apologies for the duplicated Issue assigned to you. There is an open PR that adds animation to Images. If you can improve the home page is some other way, feel free to make a PR else close this issue and pickup a new one.
