### ISSUE TITLE
Improve Home Page

### ISSUE THREAD

**Issue by afeefuddin** [algovengers/Hairify#44]
We are looking forward to refactor the home page a bit. 

Please suggest in what way you can improve the home page before demanding an assignment.

**Comment by nishant0708** [comment]
i can fix home page

**Comment by afeefuddin** [comment]
Assigned to you but don't add too much animations.

**Comment by nishant0708** [comment]
Thank You for Assigning This Issue to me . I will Make sure not to add too much animation
