### ISSUE TITLE
Add Code_of_Conduct.MD file

### ISSUE THREAD

**Issue by venkatasai24** [algovengers/Hairify#45]
As I found this issue and I'm a GSSOC'24 contributor, pls assign this to me @afeefuddin

**Comment by harikavaleti911** [comment]
Hello sir. 
Will you assign this issue to me .
And may I have any explanation about code of conduct

**Comment by afeefuddin** [comment]
Sure assigned.

**Comment by afeefuddin** [comment]
Assigned @venkatasai24 , as he claimed first. Apologies from my side, I over looked it.

**Comment by afeefuddin** [comment]
Completed in #60
