### ISSUE TITLE
Not getting responses in chat with ai

### ISSUE THREAD

**Issue by KhushiTiwarii** [algovengers/Hairify#47]
![image](https://github.com/algovengers/Hairify/assets/137861160/3efbe410-39ff-41b8-bfdb-daef7130cf98)

The chatbot is not giving any response.Please assign me this issue under gssoc'24.

**Comment by afeefuddin** [comment]
Yes there are multiple issues in the chatbot it would be great if you can fix them. One such issue is that submitting the next question button should be disabled ideally until we receive a response.

**Comment by afeefuddin** [comment]
Assigned

**Comment by KhushiTiwarii** [comment]
@afeefuddin Thankyou I'll start working on it.

**Comment by afeefuddin** [comment]
Any updates @KhushiTiwarii?
