### ISSUE TITLE
Modify the SignUp/Login page Ui for the Frontend

### ISSUE THREAD

**Issue by SumitKumar-17** [algovengers/Hairify#48]
Hi I want to work on this issue. Can you assign this issue to me under GSSoc'24?
I will make a new and responsive sign up/login Ui for the frontend part of the application

**Comment by afeefuddin** [comment]
Sure assigned.

**Comment by SumitKumar-17** [comment]
Thanks I will start working on it

**Comment by SumitKumar-17** [comment]
@afeefuddin I have completed the feature and open a PR for it . Please have a look on it .

**Comment by Tanishasi** [comment]
Hello, if the issue is up for modifying the signup and login then please assign it to me, I would like to work on it. Thank You!

**Comment by SumitKumar-17** [comment]
@afeefuddin sure I will complete it by today

**Comment by afeefuddin** [comment]
Completed in #73
