### ISSUE TITLE
Add a Contributing Guide

### ISSUE THREAD

**Issue by afeefuddin** [algovengers/Hairify#64]
Elaborate the Steps on how to Contribute, claim and tag issues.
The PR should be clean and clear.

**Comment by Madhu-mac** [comment]
Can u assaign me the issue! I would like to work on it @afeefuddin

**Comment by afeefuddin** [comment]
Assigned

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by afeefuddin** [comment]
Assigned to you @suhanipaliwal
