### ISSUE TITLE
Navbar and Contact US

### ISSUE THREAD

**Issue by gupta-ritik** [algovengers/Hairify#70]
missing of Navbar and Contact Us page in the website.
Assign this work to me resolve issues.
Importance of the Navbar and Contact Us page in the website .
The navbar is pivotal for website navigation, offering intuitive access to different sections and enhancing user experience through consistent design. It serves as a branding tool, reinforcing identity and ensuring responsive design for various devices. The Contact Us page fosters direct communication, building trust and credibility. It doubles as a customer support portal, facilitating inquiries and feedback. It's a lead generation tool, capturing potential leads through contact forms. Offering multiple contact options accommodates diverse user preferences, while accessibility features ensure inclusivity. Both elements are crucial for user engagement, trust-building, and achieving website objectives effectively.

**Comment by PPravalika17** [comment]
Assign this issue to me ,I can do it really weel

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me.

**Comment by afeefuddin** [comment]
We don't need a contact us page.
