### ISSUE TITLE
Add clear chat feature

### ISSUE THREAD

**Issue by afeefuddin** [algovengers/Hairify#84]
When we chat with the chatbot we retain history, there should be a button to clear the chat history

**Comment by mukulpythondev** [comment]
@afeefuddin I am happy to contribute for this issue.

**Comment by Madhu-mac** [comment]
@afeefuddin Im currently working on this issue, Assign it to me I'll raise a PR right away

**Comment by Madhu-mac** [comment]
@afeefuddin Where do you want me to keep the clear chat button and give me some designs, how you want it to be shown in the website?..

**Comment by afeefuddin** [comment]
Assigned to @mukulpythondev, as he requested first

**Comment by Madhu-mac** [comment]
> Assigned to @mukulpythondev, as he requested first

I've already solved it tho...

**Comment by afeefuddin** [comment]
Assigned @Madhu-mac

**Comment by Madhu-mac** [comment]
> @afeefuddin Where do you want me to keep the clear chat button and give me some designs, how you want it to be shown in the website?..

@afeefuddin Can you specify this!!

**Comment by afeefuddin** [comment]
It would be nice if you make a PR once by implementing the logic. We can do design discussions in the PR.

**Comment by Madhu-mac** [comment]
> It would be nice if you make a PR once by implementing the logic. We can do design discussions in the PR.

Cool

**Comment by afeefuddin** [comment]
Are you still working on this @Madhu-mac ?

**Comment by Madhu-mac** [comment]
> Are you still working on this @Madhu-mac ?

Yes!! I'll raise a PR tonight

**Comment by DhruvChadha22** [comment]
Hi, I would like to work on this issue under gssoc.

**Comment by DhruvChadha22** [comment]
@afeefuddin Please assign this issue to me, I have already worked out a solution for this.

**Comment by afeefuddin** [comment]
Go ahead @DhruvChadha22
