### ISSUE TITLE
Adding favicon to the website

### ISSUE THREAD

**Issue by Madhu-mac** [algovengers/Hairify#88]
As we notice the website doesn't have any favicon in place, it makes the website unnotice in some reasons..

![image](https://github.com/algovengers/Hairify/assets/99901964/6d6d094f-a8a0-424c-8968-e8ae5318912e)

**Expected solution:**
We need to update it with our navbar harify logo to the favicon..

![image](https://github.com/algovengers/Hairify/assets/99901964/a8aec0b9-71cf-4723-abd4-a81961b38157)

**Comment by Madhu-mac** [comment]
@afeefuddin Assign this issue to me and add labels to it, so that i can work and made a PR under GSSoC

**Comment by afeefuddin** [comment]
Assigned @Madhu-mac

**Comment by Madhu-mac** [comment]
@afeefuddin Can you chech the PR..
