### ISSUE TITLE
It shows Signing in when Signing up

### ISSUE THREAD

**Issue by Rakshit-gen** [algovengers/Hairify#92]
When we click on sign up after entering data it shows signing in instead of Registering or signing up.

![image](https://github.com/algovengers/Hairify/assets/64471316/25abfc78-88bc-4c24-9b37-cc9daed1996d)

We can change what it says 

Please assign this issue to me!
I am GSSoC '24 contributor

**Comment by afeefuddin** [comment]
Sure, Assigned @Rakshit-gen
