### ISSUE TITLE
Fixing the sign up page .(adding option)

### ISSUE THREAD

**Issue by akshaydubey05** [algovengers/Hairify#95]
**ISSUE** -- when creating a new user and entering password people might put wrong password. Therefore adding a " **Confirm 
                     Password** " option, and when both password and confirm password are same then the user will be created .

![Screenshot 2024-05-14 122132](https://github.com/algovengers/Hairify/assets/123586645/a2fe3f3d-975a-4b40-8605-51cbbf43d2dd)

**Comment by akshaydubey05** [comment]
Hi, i created this issue please can you assign this issue to me under GSSOC'24. Also if you want i can make the box look curvy at the ends.
Thanks

**Comment by afeefuddin** [comment]
Assigned @akshaydubey05

**Comment by afeefuddin** [comment]
Completed in #105
